CREATE TABLE IF NOT EXISTS person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_type VARCHAR(20) NOT NULL,
    name VARCHAR(255),
    meet_email VARCHAR(255),
    google_user_id VARCHAR(255),
    meet_display_name VARCHAR(255),
    classroom_email VARCHAR(255),
    parent_email VARCHAR(255),
    parent_phone VARCHAR(255),
    phone VARCHAR(255),
    hourly_rate NUMERIC(38, 2),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS student (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255),
    meet_email VARCHAR(255),
    classroom_email VARCHAR(255),
    parent_email VARCHAR(255),
    parent_phone VARCHAR(255),
    google_user_id VARCHAR(255),
    meet_display_name VARCHAR(255),
    active BOOLEAN
);

CREATE TABLE IF NOT EXISTS teacher (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255),
    meet_email VARCHAR(255),
    google_user_id VARCHAR(255),
    meet_display_name VARCHAR(255),
    phone VARCHAR(255),
    hourly_rate NUMERIC(38, 2),
    active BOOLEAN
);

CREATE TABLE IF NOT EXISTS person_legacy_map (
    legacy_type VARCHAR(20) NOT NULL,
    legacy_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    PRIMARY KEY (legacy_type, legacy_id)
);

INSERT INTO person (id, person_type, name, meet_email, google_user_id, meet_display_name, classroom_email, parent_email, parent_phone, active)
SELECT s.id, 'STUDENT', s.name, s.meet_email, s.google_user_id, s.meet_display_name, s.classroom_email, s.parent_email, s.parent_phone, COALESCE(s.active, TRUE)
FROM student s
WHERE NOT EXISTS (
    SELECT 1 FROM person p WHERE p.person_type = 'STUDENT' AND p.id = s.id
);

INSERT INTO person (id, person_type, name, meet_email, google_user_id, meet_display_name, phone, hourly_rate, active)
SELECT
    CASE
        WHEN EXISTS (SELECT 1 FROM person p WHERE p.id = t.id)
            THEN t.id + COALESCE((SELECT MAX(id) FROM student), 0)
        ELSE t.id
        END,
    'TEACHER', t.name, t.meet_email, t.google_user_id, t.meet_display_name, t.phone, t.hourly_rate, COALESCE(t.active, TRUE)
FROM teacher t
WHERE NOT EXISTS (
    SELECT 1 FROM person p
    WHERE p.person_type = 'TEACHER'
      AND p.name = t.name
      AND ((p.meet_email IS NULL AND t.meet_email IS NULL) OR p.meet_email = t.meet_email)
);

INSERT INTO person_legacy_map (legacy_type, legacy_id, person_id)
SELECT 'STUDENT', s.id, p.id
FROM student s
JOIN person p ON p.person_type = 'STUDENT' AND p.id = s.id
WHERE NOT EXISTS (
    SELECT 1 FROM person_legacy_map m WHERE m.legacy_type = 'STUDENT' AND m.legacy_id = s.id
);

INSERT INTO person_legacy_map (legacy_type, legacy_id, person_id)
SELECT 'TEACHER', t.id, p.id
FROM teacher t
JOIN person p
  ON p.person_type = 'TEACHER'
 AND p.name = t.name
 AND ((p.meet_email IS NULL AND t.meet_email IS NULL) OR p.meet_email = t.meet_email)
WHERE NOT EXISTS (
    SELECT 1 FROM person_legacy_map m WHERE m.legacy_type = 'TEACHER' AND m.legacy_id = t.id
);

CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT,
    calendar_event_id VARCHAR(255),
    event_title VARCHAR(255),
    date DATE,
    status VARCHAR(255),
    updated_at TIMESTAMP
);

ALTER TABLE attendance ADD COLUMN IF NOT EXISTS person_id BIGINT;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS student_id BIGINT;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS teacher_id BIGINT;

UPDATE attendance a
SET person_id = (
    SELECT m.person_id FROM person_legacy_map m
    WHERE m.legacy_type = 'STUDENT' AND m.legacy_id = a.student_id
)
WHERE a.person_id IS NULL AND a.student_id IS NOT NULL;

UPDATE attendance a
SET person_id = (
    SELECT m.person_id FROM person_legacy_map m
    WHERE m.legacy_type = 'TEACHER' AND m.legacy_id = a.teacher_id
)
WHERE a.person_id IS NULL AND a.teacher_id IS NOT NULL;

ALTER TABLE attendance DROP COLUMN IF EXISTS student_id;
ALTER TABLE attendance DROP COLUMN IF EXISTS teacher_id;

ALTER TABLE attendance DROP CONSTRAINT IF EXISTS uk_attendance_person_event_date;
ALTER TABLE attendance ADD CONSTRAINT uk_attendance_person_event_date
    UNIQUE (person_id, calendar_event_id, date);
ALTER TABLE attendance DROP CONSTRAINT IF EXISTS fk_attendance_person;
ALTER TABLE attendance ADD CONSTRAINT fk_attendance_person
    FOREIGN KEY (person_id) REFERENCES person(id);

CREATE TABLE IF NOT EXISTS notification_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT,
    calendar_event_id VARCHAR(255),
    date DATE,
    type VARCHAR(255),
    message VARCHAR(255),
    sent_at TIMESTAMP,
    channel VARCHAR(255),
    recipient VARCHAR(500),
    success BOOLEAN,
    failure_reason VARCHAR(255)
);

ALTER TABLE notification_log ADD COLUMN IF NOT EXISTS person_id BIGINT;
ALTER TABLE notification_log ADD COLUMN IF NOT EXISTS student_id BIGINT;
ALTER TABLE notification_log ADD COLUMN IF NOT EXISTS teacher_id BIGINT;

UPDATE notification_log n
SET person_id = (
    SELECT m.person_id FROM person_legacy_map m
    WHERE m.legacy_type = 'STUDENT' AND m.legacy_id = n.student_id
)
WHERE n.person_id IS NULL AND n.student_id IS NOT NULL;

UPDATE notification_log n
SET person_id = (
    SELECT m.person_id FROM person_legacy_map m
    WHERE m.legacy_type = 'TEACHER' AND m.legacy_id = n.teacher_id
)
WHERE n.person_id IS NULL AND n.teacher_id IS NOT NULL;

ALTER TABLE notification_log DROP COLUMN IF EXISTS student_id;
ALTER TABLE notification_log DROP COLUMN IF EXISTS teacher_id;

ALTER TABLE notification_log DROP CONSTRAINT IF EXISTS fk_notification_log_person;
ALTER TABLE notification_log ADD CONSTRAINT fk_notification_log_person
    FOREIGN KEY (person_id) REFERENCES person(id);

DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS teacher;
DROP TABLE IF EXISTS person_legacy_map;
