CREATE TABLE IF NOT EXISTS join_attempt_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_event_id VARCHAR(255) NOT NULL,
    scheduled_start TIMESTAMP NOT NULL,
    attempted_at TIMESTAMP NOT NULL,
    date DATE NOT NULL,
    trigger_type VARCHAR(50) NOT NULL,
    status VARCHAR(100) NOT NULL,
    reason_code VARCHAR(255),
    detail_message VARCHAR(1000)
);

CREATE INDEX IF NOT EXISTS idx_join_attempt_log_today ON join_attempt_log (date, attempted_at DESC);
CREATE INDEX IF NOT EXISTS idx_join_attempt_log_idempotency
    ON join_attempt_log (calendar_event_id, date, trigger_type);
