CREATE TABLE IF NOT EXISTS join_attempt_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_event_id VARCHAR(255) NOT NULL,
    scheduled_start TIMESTAMP,
    attempted_at    TIMESTAMP NOT NULL,
    status          VARCHAR(50) NOT NULL,
    detail_message  VARCHAR(1000),
    date            DATE NOT NULL,
    trigger_type    VARCHAR(50) NOT NULL
);

ALTER TABLE join_attempt_log
    DROP CONSTRAINT IF EXISTS uk_join_attempt_log_event_date_trigger;
ALTER TABLE join_attempt_log
    ADD CONSTRAINT uk_join_attempt_log_event_date_trigger
        UNIQUE (calendar_event_id, date, trigger_type);
